name: "Terraform CI/CD Pipeline"

on:
  push:
    branches:
      - main
      - develop
# pull_request:
#   branches:
#     - main:
  workflow_dispatch:
    inputs:
      confirm_deploy:
        description: "Type GO to confirm execution"
        required: true
        default: "GO"
      confirm_destroy:
        description: "Type DO to remove the development environment"
        required: true
        default: "NO"

permissions:
  id-token: write
  contents: read

jobs:
  plan:
    name: "Terraform init & Plan"
    runs-on: ubuntu-latest

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}
    
    # Force the execution to run directly inside your dev folder
    defaults:
      run:
        working-directory: ./environments/dev

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Azure Login Auth
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: >-
          terraform init -input=false
          -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP }}"
          -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT }}"
          -backend-config="container_name=${{ vars.TFSTATE_CONTAINER }}"
          -backend-config="key=dev.terraform.tfstate"
          -backend-config="use_azuread_auth=true"
          -backend-config="use_oidc=true"

      - name: Terraform Plan
        run: terraform plan -input=false -out=tfplan

      - name: Upload Terraform Plan
        uses: actions/upload-artifact@v4
        with:
          name: terraform-dev-plan
          path: environments/dev/tfplan
          if-no-files-found: error

  apply:
    name: "Terraform Apply"
    needs: plan
    runs-on: ubuntu-latest
    if: >-
      ${{ 
         (github.event_name == 'workflow_dispatch' &&
          github.event.inputs.confirm_deploy == 'GO')
      }}

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

    # Force the execution to run directly inside your dev folder
    defaults:
      run:
        working-directory: ./environments/dev

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Azure Login Auth
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: >-
          terraform init -input=false
          -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP }}"
          -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT }}"
          -backend-config="container_name=${{ vars.TFSTATE_CONTAINER }}"
          -backend-config="key=dev.terraform.tfstate"
          -backend-config="use_azuread_auth=true"
          -backend-config="use_oidc=true"

      - name: Download Terraform Plan
        uses: actions/download-artifact@v4
        with:
          name: terraform-dev-plan
          path: environments/dev

      - name: Terraform Apply
        run: terraform apply -auto-approve -input=false tfplan

  destroy:
    name: "Terraform Destroy"
    needs: plan
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event_name == 'workflow_dispatch' &&
          github.event.inputs.confirm_destroy == 'DO' }}

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.SUBSCRIPTION_ID }}

    defaults:
      run:
        working-directory: ./environments/dev

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.7.0"

      - name: Azure Login Auth
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.CLIENT_ID }}
          tenant-id: ${{ secrets.TENANT_ID }}
          subscription-id: ${{ secrets.SUBSCRIPTION_ID }}

      - name: Terraform Init
        run: >-
          terraform init -input=false
          -backend-config="resource_group_name=${{ vars.TFSTATE_RESOURCE_GROUP }}"
          -backend-config="storage_account_name=${{ vars.TFSTATE_STORAGE_ACCOUNT }}"
          -backend-config="container_name=${{ vars.TFSTATE_CONTAINER }}"
          -backend-config="key=dev.terraform.tfstate"
          -backend-config="use_azuread_auth=true"
          -backend-config="use_oidc=true"

      - name: Terraform Destroy
        run: terraform destroy -auto-approve -input=false

      - name: Destroy storage
        run: az storage account delete --name aksterraformstorage --resource-group tfstate-rg --yes'
